# Generated by Django 2.1.1 on 2018-10-14 10:48

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Closing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('percentile', models.DecimalField(decimal_places=7, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, unique=True, validators=[api.models.validate_portfolio_name])),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=4, unique=True, validators=[api.models.validate_ticker])),
                ('portfolios', models.ManyToManyField(blank=True, to='api.Portfolio')),
            ],
        ),
        migrations.CreateModel(
            name='StockPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('value', models.DecimalField(decimal_places=2, max_digits=9)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Stock', to_field='ticker')),
            ],
        ),
        migrations.AddField(
            model_name='closing',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Stock', to_field='ticker'),
        ),
    ]
