# Generated by Django 2.1.1 on 2018-10-13 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Closing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('percentile', models.DecimalField(decimal_places=7, max_digits=7)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Stock')),
            ],
        ),
    ]
