# Generated by Django 2.1.1 on 2018-10-13 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20181013_0501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='portfolios',
            field=models.ManyToManyField(to='api.Portfolio'),
        ),
    ]
