# Generated by Django 2.1.1 on 2018-10-13 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20181013_0626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='portfolios',
            field=models.ManyToManyField(blank=True, to='api.Portfolio'),
        ),
    ]
